version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client:/app

  messaging:
    container_name: messaging
    build: ./messaging
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./messaing:/app
