version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client:/app

  messaging:
    container_name: messaging
    build: ./messaging
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./messaging:/app

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./.nginx_conf/dev_conf.d/:/etc/nginx/
    depends_on:
      - client
      - messaging
