version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    restart: always
    volumes:
      - ./client:/app

  messaging:
    container_name: messaging
    build: ./messaging
    restart: always
    volumes:
      - ./messaging:/app
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./.nginx_conf/dev_conf.d/:/etc/nginx/
    depends_on:
      - client
      - messaging
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
