version: "3"
services:
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    restart: always

  messaging:
    container_name: messaging
    build: ./messaging
    restart: always
    ports:
      - 8080:8080
